jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build --no-cache -t restaurant-app . --progress=plain
- name: Run tests
  run: docker run restaurant-app pytest